// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCm0P8U4XvT16WANCIAU4kQse_ERqKSOm8',
    appId: '1:102659453700:web:3dc79252157429a7929651',
    messagingSenderId: '102659453700',
    projectId: 'notes-flutterpro',
    authDomain: 'notes-flutterpro.firebaseapp.com',
    storageBucket: 'notes-flutterpro.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv9EcGl5MzH_qOnWQTPrsIik0uxzmlAHw',
    appId: '1:102659453700:android:04f1a990aad93577929651',
    messagingSenderId: '102659453700',
    projectId: 'notes-flutterpro',
    storageBucket: 'notes-flutterpro.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhV_X769py6g6VRfBfCY8JtnOszkPBD6I',
    appId: '1:102659453700:ios:907bcc7fcd437613929651',
    messagingSenderId: '102659453700',
    projectId: 'notes-flutterpro',
    storageBucket: 'notes-flutterpro.appspot.com',
    iosClientId:
        '102659453700-9180gj0495ua4c4f63gs7nmlbe8t5aob.apps.googleusercontent.com',
    iosBundleId: 'com.hello.note',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhV_X769py6g6VRfBfCY8JtnOszkPBD6I',
    appId: '1:102659453700:ios:907bcc7fcd437613929651',
    messagingSenderId: '102659453700',
    projectId: 'notes-flutterpro',
    storageBucket: 'notes-flutterpro.appspot.com',
    iosClientId:
        '102659453700-9180gj0495ua4c4f63gs7nmlbe8t5aob.apps.googleusercontent.com',
    iosBundleId: 'com.hello.note',
  );
}
